package JavaChat.Common.Transfer;

import java.io.Serializable;

/**
 * 此类为枚举类,用来反馈给客户端相关业务处理情况
 */
public enum ServerRespond implements MessageType {
    //登录
    LOGIN_SUCCEED,
    LOGIN_FAIL_ERROR,
    LOGIN_FAIL_REPEAT_LOGIN,

    //退出登录
    EXIT_LOGIN_SUCCEED,
    EXIT_LOGIN_FAIL,

    //注册
    REGISTER_SUCCEED,
    REGISTER_EMAIL_OCCUPIED,
    REGISTER_VERIFICATION_CODE_ERROR,
    REGISTER_VERIFICATION_CODE_NOT_SEND,

    //忘记密码
    FORGET_SUCCEED,
    FORGET_EMAIL_IS_NOT_RIGHT,
    FORGET_VERIFICATION_CODE_ERROR,
    FORGET_VERIFICATION_CODE_NOT_SEND,

    //发送文本消息
    SEND_TEXT_MESSAGE_SUCCEED_TO_ACTIVE,
    SEND_TEXT_MESSAGE_SUCCEED_TO_PASSIVE,
    SEND_TEXT_MESSAGE_FAIL,

    //发送图片消息
    SEND_IMAGE_MESSAGE_SUCCEED_ACTIVE,
    SEND_IMAGE_MESSAGE_SUCCEED_PASSIVE,

    //发送文件消息
    SEND_FILE_MESSAGE_TO_ACTIVE,
    SEND_FILE_MESSAGE_TO_PASSIVE,
    AGREE_FILE_MESSAGE_TO_ACTIVE,
    AGREE_FILE_MESSAGE_TO_PASSIVE,
    REJECT_FILE_MESSAGE_TO_ACTIVE,
    REJECT_FILE_MESSAGE_TO_PASSIVE,

    //发送注册的验证码
    SEND_REGISTER_EMAIL_REPEAT,
    SEND_REGISTER_EMAIL_SUCCEED,

    //发送忘记密码的验证码
    SEND_FORGET_EMAIL_REPEAT,
    SEND_FORGET_EMAIL_SUCCEED,

    //修改密码
    ALTER_PASSWORD_SUCCEED,
    ALTER_PASSWORD_EMAIL_IS_NOT_RIGHT,
    ALTER_PASSWORD_VERIFICATION_CODE_ERROR,
    ALTER_PASSWORD_VERIFICATION_CODE_NOT_SEND,

    //发送修改密码验证码
    SEND_ALTER_PASSWORD_EMAIL_REPEAT,
    SEND_ALTER_PASSWORD_EMAIL_SUCCEED,

    //获取好友列表
    PULL_FRIEND_LIST_SUCCEED,
    PULL_FRIEND_LIST_FAIL,

    //获取消息列表
    PULL_MESSAGE_LIST_FAIL,
    PULL_MESSAGE_LIST_SUCCEED,

    //好友申请发送
    TRANSMIT_APPLICATION_TO_ACTIVE_SUCCEED,
    TRANSMIT_APPLICATION_TO_PASSIVE_SUCCEED,
    ADD_FRIEND_APPLICATION_SEND_FAIL_REPEAT,
    ADD_FRIEND_APPLICATION_SEND_FAIL_HAVE_BE_FRIEND,
    ADD_FRIEND_APPLICATION_SEND_FAIL_MYSELF,

    //同意好友申请好友申请的处理
    AGREE_FRIEND_APPLICATION_TO_ACTIVE_SUCCEED,
    AGREE_FRIEND_APPLICATION_TO_PASSIVE_SUCCEED,

    //拒绝好友申请
    REJECT_FRIEND_APPLICATION_TO_ACTIVE_SUCCEED,
    REJECT_FRIEND_APPLICATION_TO_PASSIVE_SUCCEED,

    //拉取好友申请列表
    PULL_ADD_FRIEND_APPLICATION_LIST_SUCCEED,
    PULL_ADD_FRIEND_APPLICATION_LIST_FAIL,

    //删除好友
    DELETE_FRIEND_SUCCEED_TO_ACTIVE,
    DELETE_FRIEND_SUCCEED_TO_PASSIVE,
    DELETE_FRIEND_FAIL,

    //搜索好友
    SEARCH_USER_SUCCEED,
    SEARCH_USER_FAIL,

    //修改个人信息
    ALTER_PERSON_INFORMATION_SUCCEED,
    ALTER_PERSON_INFORMATION_FAIL,

    //创建群聊
    CREAT_GROUP_SUCCEED,
    CREAT_GROUP_FAIL,

    //添加群聊
    ENTER_GROUP_SUCCEED_TO_PASSIVE_ADMINISTRATOR,
    ENTER_GROUP_SUCCEED_TO_ACTIVE,
    ENTER_GROUP_FAIL_REPEAT,
    ENTER_GROUP_FAIL_HAVE_IN_GROUP,


    //搜索群聊
    SEARCH_GROUP_SUCCEED,
    SEARCH_GROUP_FAIL,

    //退出群聊
    EXIT_GROUP_SUCCEED,
    EXIT_GROUP_SUCCEED_TO_ACTIVE,
    EXIT_GROUP_SUCCEED_TO_PASSIVE,
    EXIT_GROUP_FAIL,

    //解散群聊
    DISSOLUTION_GROUP_SUCCEED_ACTIVE,
    DISSOLUTION_GROUP_SUCCEED_PASSIVE,
    DISSOLUTION_GROUP_FAIL,

    //删除群成员
    DELETE_GROUP_MEMBER_SUCCEED_ACTIVE,
    DELETE_GROUP_MEMBER_SUCCEED_PASSIVE,
    DELETE_GROUP_MEMBER_FAIL,


    //修改群资料
    ALTER_GROUP_DATA_SUCCEED,
    ALTER_GROUP_DATA_FAIL,

    //群聊发文本消息
    SEND_GROUP_TEXT_MESSAGE_SUCCEED_TO_ACTIVE,
    SEND_GROUP_TEXT_MESSAGE_SUCCEED_TO_PASSIVE,


    //拉取某个账号加入的所有群
    PULL_GROUP_LIST_SUCCEED,
    PULL_GROUP_LIST_FAIL,

    //拉取某个群的群聊消息
    PULL_GROUP_MESSAGE_SUCCEED,
    PULL_GROUP_MESSAGE_FAIL,

    //拉取某个群的申请
    PULL_GROUP_APPLICATION_LIST_SUCCEED,
    PULL_GROUP_APPLICATION_LIST_FAIL,

    //同意某人进群
    AGREE_GROUP_APPLICATION_TO_ACTIVE,
    AGREE_GROUP_APPLICATION_TO_PASSIVE_ADMINISTRATORS,//此被动方为该群的群主和管理员
    AGREE_GROUP_APPLICATION_TO_PASSIVE_SENDER,//让这个人进群

    //拒绝某人进群
    REJECT_GROUP_APPLICATION_TO_ACTIVE,
    REJECT_GROUP_APPLICATION_TO_PASSIVE_ADMINISTRATORS,
    REJECT_GROUP_APPLICATION_TO_PASSIVE_SENDER,

    //身份不能处理该群申请
    GROUP_APPLICATION_INSUFFICIENT_PERMISSIONS,

    //该群申请已经被处理过了
    GROUP_APPLICATION_HAD_BEEN_PROCESSED,


    //设置管理员
    SET_GROUP_ADMINISTRATORS_SUCCEED_ACTIVE,
    SET_GROUP_ADMINISTRATORS_SUCCEED_PASSIVE,
    SET_GROUP_ADMINISTRATORS_FAIL,

    //撤职管理员
    DISMISSAL_GROUP_ADMINISTRATORS_SUCCEED_ACTIVE,
    DISMISSAL_GROUP_ADMINISTRATORS_SUCCEED_PASSIVE,
    DISMISSAL_GROUP_ADMINISTRATORS_FAIL,

    //下线通知
    OFFLINE_NOTIFICATION,

    //上线通知
    ONLINE_NOTIFICATION,

    //拉取管理群所需要的资源
    PULL_MANAGE_GROUP_RESOURCE_SUCCEED,

    //拉取群通知
    PULL_GROUP_NOTICE_SUCCEED,
    PULL_GROUP_NOTICE_FAIL,

    //添加表情
    ADD_EMOJI_SUCCEED,
    ADD_EMOJI_FAIL,

    //删除表情
    DELETE_EMOJI_SUCCEED,
    DELETE_EMOJI_FAIL,

    //拉取表情
    PULL_EMOJI_SUCCEED,
    PULL_EMOJI_FAIL,

    //拉取user
    PULL_USER_FROM_ACCOUNT_SUCCEED,
    PULL_USER_FROM_ACCOUNT_FAIL,


}
